stages:
  read_data:
    cmd:
    - python scripts/get_data.py
    deps:
    - scripts/get_data.py
    outs:
    - data/raw
  merge_concatenate:
    cmd:
    - python scripts/merge_concatenate.py
    deps:
    - scripts/merge_concatenate.py
    - data/raw
    outs:
    - notebooks/all_2011_df.csv
    - notebooks/all_2013_df.csv
    - notebooks/all_2015_df.csv
    - notebooks/all_data_df.csv
  final_lda_results:
    cmd:
    - python scripts/final_lda_results.py
    deps:
    - scripts/final_lda_results.py
    - notebooks
    outs:
    - notebooks/final_lda_results.csv
  final_lr_results:
    cmd:
    - python scripts/final_lr_results.py
    deps:
    - scripts/final_lr_results.py
    - notebooks
    outs:
    - notebooks/final_lr_results.csv
  final_naive_bayes_results:
    cmd:
    - python scripts/final_naive_bayes_results.py
    deps:
    - scripts/final_naive_bayes_results.py
    - notebooks
    outs:
    - notebooks/final_nb_results.csv
  final_random_forest_results:
    cmd:
    - python scripts/final_random_forest_results.py
    deps:
    - scripts/final_random_forest_results.py
    - notebooks
    outs:
    - notebooks/final_rf_results.csv
